package com.module.autographs.carregistration.microservice.util;

public class Constants {

    // HTTP STATUS CODES
    public static final String HTTP_RESPONSE_CODE_OK = "200";
    public static final String HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = "500";

    // ALL API PATHS

    // 1 - NEW CAR REGISTRATIONS
    public static final String NEW_CAR_REGISTRATION_GET_API_PATH = "/getAllNewCarRegistrationsData";
    public static final String NEW_CAR_REGISTRATION_POST_API_PATH = "/addNewCarRegistrationsData";
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_API_PATH = "/deleteAllNewCarRegistrationsData";
    public static final String NEW_CAR_REGISTRATION_BY_QUERY_GET_API_PATH = "/getAllNewCarRegistrationsDataByQuery";

    // 2 - NEW CAR REGISTRATIONS BY FUEL TYPE
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_GET_API_PATH = "/getAllNewCarRegistrationsByFuelTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_POST_API_PATH = "/addNewCarRegistrationsByFuelTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewCarRegistrationsByFuelTypeData";

    // 3 - NEW CAR REGISTRATIONS BY SALES TYPE
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_GET_API_PATH = "/getAllNewCarRegistrationsBySalesTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_POST_API_PATH = "/addNewCarRegistrationsBySalesTypeData";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewCarRegistrationsBySalesTypeData";


    // ALL SWAGGER CONSTANTS BELOW ---------------------------------------------------------------------------------------------------------

    // 1 - NEW CAR REGISTRATIONS
    // GET API
    public static final String NEW_CAR_REGISTRATION_GET_SUMMARY = "GET - NEW CAR REGISTRATION DATA";
    public static final String NEW_CAR_REGISTRATION_SUCCESS = "NEW CAR REGISTRATION DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION.";
    // GET API BY QUERY
    public static final String NEW_CAR_REGISTRATION_GET_BY_QUERY_SUMMARY = "GET - NEW CAR REGISTRATION DATA";
    public static final String NEW_CAR_REGISTRATION_GET_BY_QUERY_SUCCESS = "NEW CAR REGISTRATION DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_GET_BY_QUERY_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION.";
    // POST API
    public static final String NEW_CAR_REGISTRATION_POST_SUMMARY = "POST - ADD NEW CAR REGISTRATIONS";
    public static final String NEW_CAR_REGISTRATION_ADD_SUCCESS = "NEW CAR REGISTRATIONS DATA ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR REGISTRATION DATA.";
    // DELETE API
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR REGISTRATION DATA";
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_SUCCESS = "NEW CAR REGISTRATION DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR REGISTRATION DATA.";

    // 2 - NEW CAR REGISTRATIONS BY FUEL TYPE
    // GET API
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_GET_SUMMARY = "GET - NEW CAR REGISTRATION BY FUEL TYPE DATA";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_SUCCESS = "NEW CAR REGISTRATION BY FUEL TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION BY FUEL TYPE.";
    // POST API
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_POST_SUMMARY = "POST - ADD NEW CAR REGISTRATION BY FUEL TYPE";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_ADD_SUCCESS = "NEW CAR REGISTRATIONS DATA BY FUEL TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR REGISTRATION BY FUEL TYPE DATA.";
    // DELETE API
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR REGISTRATION BY FUEL TYPE  DATA";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_SUCCESS = "NEW CAR REGISTRATION BY FUEL TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_FUEL_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR REGISTRATION BY FUEL TYPE DATA.";

    // 3 - NEW CAR REGISTRATIONS BY SALES TYPE
    // GET API
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_GET_SUMMARY = "GET - NEW CAR REGISTRATION BY SALES TYPE DATA";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_SUCCESS = "NEW CAR REGISTRATION BY SALES TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR REGISTRATION BY SALES TYPE.";
    // POST API
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_POST_SUMMARY = "POST - ADD NEW CAR REGISTRATION BY SALES TYPE";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_ADD_SUCCESS = "NEW CAR REGISTRATIONS DATA BY SALES TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR REGISTRATION BY SALES TYPE DATA.";
    // DELETE API
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR REGISTRATION BY SALES TYPE  DATA";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_SUCCESS = "NEW CAR REGISTRATION BY SALES TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_REGISTRATION_BY_SALES_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR REGISTRATION BY SALES TYPE DATA.";


}
